### ISSUE TITLE
[Bitfinex Branch] linux python3 dependencies

### ISSUE THREAD

**Issue by njsalvador** [nunoloureiro/birdtradebot#8]
Hi,

I was trying to install this bitfinex branch development but I stuck in dependencies:
- gdax requires requests==2.13.0
- latest version of ccxt requires requests>=2.18.4

I had to install ccxt==1.9.389 in order to make it work. 

 pip list
aiodns            1.1.1
aiohttp           3.2.0
async-timeout     3.0.0
attrs             18.1.0
bintrees          2.0.7
birdtradebot      0.3.0     /home/user/birdtradebot
cchardet          2.1.1
cctx              1.0.0
ccxt              1.9.389
certifi           2018.1.18
chardet           3.0.4
crypto            1.4.1
gdax              1.0.6
idna              2.6
idna-ssl          1.0.1
multidict         4.3.1
Naked             0.1.31
oauthlib          2.0.7
pip               10.0.1
pycares           2.3.0
pycrypto          2.6.1
pycryptodome      3.6.1
python-dateutil   2.7.2
PyYAML            3.12
requests          2.13.0
requests-oauthlib 0.8.0
setuptools        39.1.0
shellescape       3.4.1
six               1.10.0
twython           3.7.0
urllib3           1.22
virtualenv        15.2.0
websocket-client  0.40.0
wheel             0.31.0
yarl              1.2.4

Which versions of gdax, requests and ccxt are you using?

**Comment by poupas** [comment]
Hi, try installing the dependencies with `pip install .`  (using pip from your virtualenv). It should install the latest requests version.

**Comment by njsalvador** [comment]
Yes I used pip. Didn't help.

```
pip install --upgrade ccxt
(...)
gdax 1.0.6 has requirement requests==2.13.0, but you'll have requests 2.18.4 which is incompatible.
Installing collected packages: yarl, requests, ccxt
  Found existing installation: yarl 1.2.4
    Uninstalling yarl-1.2.4:
      Successfully uninstalled yarl-1.2.4
  Found existing installation: requests 2.13.0
    Uninstalling requests-2.13.0:
      Successfully uninstalled requests-2.13.0
  Found existing installation: ccxt 1.9.389
    Uninstalling ccxt-1.9.389:
      Successfully uninstalled ccxt-1.9.389
Successfully installed ccxt-1.13.115 requests-2.18.4 yarl-1.1.0

(srvbird) [user@server ~]$ birdtradebot configure
Traceback (most recent call last):
  File "/home/user/srvbird/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/home/user/srvbird/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/user/srvbird/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.18.4 (/home/user/srvbird/lib/python3.6/dist-packages), Requirement.parse('requests==2.13.0'), {'gdax'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/srvbird/bin/birdtradebot", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/user/srvbird/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3147, in <module>
    @_call_aside
  File "/home/user/srvbird/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "/home/user/srvbird/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/user/srvbird/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 668, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/user/srvbird/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 681, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/user/srvbird/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.18.4 (/home/user/srvbird/lib/python3.6/dist-packages), Requirement.parse('requests==2.13.0'), {'gdax'})

(srvbird) [user@server ~]$ pip install --upgrade gdax
Requirement already up-to-date: gdax in ./srvbird/lib/python3.6/dist-packages (1.0.6)
Requirement not upgraded as not directly required: six==1.10.0 in ./srvbird/lib/python3.6/dist-packages (from gdax) (1.10.0)
Collecting requests==2.13.0 (from gdax)
  Using cached https://files.pythonhosted.org/packages/7e/ac/a80ed043485a3764053f59ca92f809cc8a18344692817152b0e8bd3ca891/requests-2.13.0-py2.py3-none-any.whl
Requirement not upgraded as not directly required: websocket-client==0.40.0 in ./srvbird/lib/python3.6/dist-packages (from gdax) (0.40.0)
Requirement not upgraded as not directly required: bintrees==2.0.7 in ./srvbird/lib/python3.6/dist-packages (from gdax) (2.0.7)
ccxt 1.13.115 has requirement requests>=2.18.4, but you'll have requests 2.13.0 which is incompatible.
Installing collected packages: requests
  Found existing installation: requests 2.18.4
    Uninstalling requests-2.18.4:
      Successfully uninstalled requests-2.18.4
Successfully installed requests-2.13.0
```

**Comment by poupas** [comment]
Since you're running Python 3.6, could you please test the [sub-accounts](https://github.com/nunoloureiro/birdtradebot/tree/sub-accounts) branch?

It should solve the version compatibility issues.

Note that the config file format is different, but this bot version has some nice features. One of them is the support for "virtual accounts" inside an exchange. Imagine that you have 1 ETH in your account (GDAX or Bitfinex). You could create a virtual account with 0.5 ETH that follows one bot and another that follows a different bot, or have different rules. This allows you to test different strategies against each other, all with a single account. It also allows you to follow, on the same account, for example, ETH and BTC each with different fiat (EUR/USD) balances.

**Comment by njsalvador** [comment]
Wow. Very nice. Already running the sub-accounts branch! :)

I also understood that the problem was with gdax version 1.0.6, despite being the stable and published version, it is old.

This configuration installs gdax 1.0.7.

Thanks.

**Comment by poupas** [comment]
I will close this issue. Feel free to open any additional issue as required :)
